library(readr)
library(dplyr)
library(stringr)
library(udpipe)
library(keras)
library(tensorflow)
library(reticulate)
library(quanteda)
library(tidytext)
library(tm)
library(word2vec)
library(tibble)
library(koRpus)

R.version.string
#is_keras_available()
#py_module_available("tensorflow")
use_virtualenv("C:/Users/Ethan/Documents/.virtualenvs/r-tensorflow", required = TRUE)
file_path <- ("C:\\Users\\Ethan\\OneDrive\\Cloud_Desktop\\00_UC\\00_2025_S2\\00_LING\\00_analysis\\data_sets")
