---
title: "NLP"
author: "74465159 Ethan Milne"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("01_processing.Rmd")
```

# NLP processes
```{r}
true_df <- one_sentence_true
fake_df <- one_sentence_fake

udmodel <- udpipe_download_model(language = "english-ewt")
udmodel <- udpipe_load_model(file = udmodel$file_model)
```

```{r}
# df testing space

```



```{r}
annotations <- udpipe_annotate(udmodel, x = true_df$first_sentence, doc_id = df$entry)
annotations <- udpipe_annotate(udmodel, x = fake_df$first_sentence, doc_id = df$entry)

true_annotations_df <- as.data.frame(annotations)
fake_annotations_df <- as.data.frame(annotations)
```

```{r}
# annotations_df testing space

```

```{r}
true_noun_chunks <- keywords_phrases(
  x = true_annotations_df$upos,
  term = annotations_df$token,
  pattern = "(DET )?(ADJ )*NOUN",
  is_regex = TRUE,
  detailed = TRUE
)

fake_noun_chunks <- keywords_phrases(
  x = fake_annotations_df$upos,
  term = annotations_df$token,
  pattern = "(DET )?(ADJ )*NOUN",
  is_regex = TRUE,
  detailed = TRUE
)
```


```{r}
# True adverbial clauses
adv_clauses_true <- true_annotations_df %>%
  group_by(doc_id) %>%
  group_modify(~{
    advcl_tokens <- .x %>% dplyr::filter(dep_rel == "advcl")
    if (nrow(advcl_tokens) == 0) {
      return(tibble(type = character(), clause = character()))
    }
    clause_list <- lapply(advcl_tokens$token_id, function(id) {
      ids <- get_subtree_ids(.x, id)
      clause_tokens <- .x %>% dplyr::filter(token_id %in% ids)
      paste(clause_tokens$token, collapse = " ")
    })
    tibble(type = "Adverbial Clause", clause = unlist(clause_list))
  })

# Fake adverbial clauses
adv_clauses_fake <- fake_annotations_df %>%
  group_by(doc_id) %>%
  group_modify(~{
    advcl_tokens <- .x %>% dplyr::filter(dep_rel == "advcl")
    if (nrow(advcl_tokens) == 0) {
      return(tibble(type = character(), clause = character()))
    }
    clause_list <- lapply(advcl_tokens$token_id, function(id) {
      ids <- get_subtree_ids(.x, id)
      clause_tokens <- .x %>% dplyr::filter(token_id %in% ids)
      paste(clause_tokens$token, collapse = " ")
    })
    tibble(type = "Adverbial Clause", clause = unlist(clause_list))
  })
```