---
title: "workbench"
author: "74465159 Ethan Milne"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("02_evaluating.Rmd")
```

```{r}
df <- one_sentence_fake

udmodel <- udpipe_download_model(language = "english-ewt")

udmodel <- udpipe_load_model(file = udmodel$file_model)
```

```{r}
# df testing space

```



```{r}
annotations <- udpipe_annotate(udmodel, x = df$first_sentence, doc_id = df$entry)

annotations_df <- as.data.frame(annotations)
```

```{r}
# annotations_df testing space

str(annotations_df)
```



```{r}
noun_phrases <- annotations_df %>%
  dplyr::filter(upos == "NOUN" | upos == "PROPN") %>%
  group_by(doc_id) %>%
  summarise(phrase = paste(token, collapse = " "), .groups = "drop")

```

```{r}
get_subtree_ids <- function(tokens, head_id) {
  ids <- c(head_id)
  repeat {
    new_ids <- tokens$token_id[tokens$head_token_id %in% ids & !(tokens$token_id %in% ids)]
    if (length(new_ids) == 0) break
    ids <- c(ids, new_ids)
  }
  ids
}


adv_clauses <- annotations_df %>%
  group_by(doc_id) %>%
  group_modify(~{
    advcl_tokens <- .x %>% dplyr::filter(dep_rel == "advcl")
    if (nrow(advcl_tokens) == 0) {
      return(tibble(type = character(), clause = character()))
    }
    clause_list <- lapply(advcl_tokens$token_id, function(id) {
      ids <- get_subtree_ids(.x, id)
      clause_tokens <- .x %>% dplyr::filter(token_id %in% ids)
      paste(clause_tokens$token, collapse = " ")
    })
    tibble(type = "Adverbial Clause", clause = unlist(clause_list))
  })
```


```{r}
View(adv_clauses)
View(noun_phrases)
```


```{r}
# Create dummy data: each row represents a sentence
set.seed(123)
dummy_data <- data.frame(
  sentence_id = 1:20,
  has_noun_phrase = sample(c(TRUE, FALSE), 20, replace = TRUE),
  has_adv_clause = sample(c(TRUE, FALSE), 20, replace = TRUE)
)

# Convert data to long format for plotting
plot_data <- dummy_data %>%
  pivot_longer(
    cols = c(has_noun_phrase, has_adv_clause),
    names_to = "phrase_type",
    values_to = "has_phrase"
  ) %>%
  mutate(
    phrase_type = recode(phrase_type,
      has_noun_phrase = "Noun Phrase",
      has_adv_clause = "Adverbial Clause"
    ),
    has_phrase = ifelse(has_phrase, "True", "False")
  )

# Plot
ggplot(plot_data, aes(x = has_phrase, fill = has_phrase)) +
  geom_bar() +
  facet_wrap(~ phrase_type) +
  labs(
    title = "Presence of Noun Phrases and Adverbial Clauses (Dummy Data)",
    x = "Contains Phrase",
    y = "Number of Sentences"
  ) +
  scale_fill_manual(values = c("True" = "steelblue", "False" = "gray70")) +
  theme_minimal()

```